package ru.robinhood.TelegramBotRobinHoodCapital.util.enums;

public enum AdminButton {
    SHOW_WALLET_NUMBER, GO_BACK_INFERENCE, CONFIRM_INFERENCE,
    SHOW_INFERENCE_TRUE,
    SHOW_INFERENCE_FALSE,
    SHOW_INFERENCE_ALL,
    RESPONSE_HELP_MESSAGE,
    GO_BACK_TOPIC_MESSAGES,
    EDIT_WALLET_NUMBER,
    CANCEL_EDIT_WALLET_NUMBER,
    SHOW_PROCESSED_HELP_MESSAGE,
    SHOW_PROCESSED_EDIT_WALLET, SHOW_UNPROCESSED_EDIT_WALLET, SHOW_UNPROCESSED_HELP_MESSAGE
}
