package ru.robinhood.TelegramBotRobinHoodCapital.util.enums;

public enum FAQ {
    HOW_DEPOSIT_BALANCE,
    HOW_EDIT_ADDRESS_WALLET, HOW_CALCULATE_FINAL_AMOUNT, HOW_GET_BONUS, HOW_GET_BONUS_INVITED, HOW_LINK_WALLET, HOW_INFERENCE_BALANCE
}
